# Generated by Django 4.1.7 on 2023-04-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_all_categories_mumbai'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='all_categories_mumbai',
            name='categories',
            field=models.CharField(max_length=255),
        ),
    ]
