# Generated by Django 4.1.7 on 2023-04-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_user_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_categories',
            name='all_spots',
            field=models.CharField(default=['null'], max_length=510),
            preserve_default=False,
        ),
    ]
