# Generated by Django 4.2 on 2023-04-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_user_categories_all_spots'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabu_total_time', models.CharField(max_length=510)),
                ('tabu_distance', models.CharField(max_length=510)),
                ('genetic_route_total_time', models.CharField(max_length=510)),
                ('genetic_distance', models.CharField(max_length=510)),
                ('simulated_annealing_total_time', models.CharField(max_length=510)),
                ('simulated_annealing_distance', models.CharField(max_length=510)),
                ('top_loc_name_dis_time', models.CharField(max_length=100000)),
            ],
        ),
    ]
