# Generated by Django 4.2 on 2023-04-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_user_output_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_output',
            name='genetic_route',
            field=models.CharField(default='judfhsdo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_output',
            name='simulated_annealing_route',
            field=models.CharField(default='duifhnsdo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_output',
            name='tabu_route',
            field=models.CharField(default='dfjuhsdfoi', max_length=255),
            preserve_default=False,
        ),
    ]
