# Generated by Django 4.2 on 2023-04-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_user_output_genetic_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_output',
            name='best_route',
            field=models.CharField(default='jghdjkf', max_length=255),
            preserve_default=False,
        ),
    ]
