# Generated by Django 4.2 on 2023-04-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_user_output_best_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_output',
            name='current_location',
            field=models.CharField(default='fd', max_length=255),
            preserve_default=False,
        ),
    ]
