# Generated by Django 4.1.2 on 2023-05-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_all_categories_delhi_user_output_mumbai_user_output_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chennai_User_Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('tabu_total_time', models.CharField(max_length=510)),
                ('tabu_distance', models.CharField(max_length=510)),
                ('genetic_route_total_time', models.CharField(max_length=510)),
                ('genetic_distance', models.CharField(max_length=510)),
                ('simulated_annealing_total_time', models.CharField(max_length=510)),
                ('simulated_annealing_distance', models.CharField(max_length=510)),
                ('tabu_route', models.CharField(max_length=255)),
                ('genetic_route', models.CharField(max_length=255)),
                ('simulated_annealing_route', models.CharField(max_length=255)),
                ('best_route', models.CharField(max_length=255)),
                ('current_location', models.CharField(max_length=255)),
                ('top_loc_name_dis_time', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Jaipur_User_Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('tabu_total_time', models.CharField(max_length=510)),
                ('tabu_distance', models.CharField(max_length=510)),
                ('genetic_route_total_time', models.CharField(max_length=510)),
                ('genetic_distance', models.CharField(max_length=510)),
                ('simulated_annealing_total_time', models.CharField(max_length=510)),
                ('simulated_annealing_distance', models.CharField(max_length=510)),
                ('tabu_route', models.CharField(max_length=255)),
                ('genetic_route', models.CharField(max_length=255)),
                ('simulated_annealing_route', models.CharField(max_length=255)),
                ('best_route', models.CharField(max_length=255)),
                ('current_location', models.CharField(max_length=255)),
                ('top_loc_name_dis_time', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Kolkata_User_Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('tabu_total_time', models.CharField(max_length=510)),
                ('tabu_distance', models.CharField(max_length=510)),
                ('genetic_route_total_time', models.CharField(max_length=510)),
                ('genetic_distance', models.CharField(max_length=510)),
                ('simulated_annealing_total_time', models.CharField(max_length=510)),
                ('simulated_annealing_distance', models.CharField(max_length=510)),
                ('tabu_route', models.CharField(max_length=255)),
                ('genetic_route', models.CharField(max_length=255)),
                ('simulated_annealing_route', models.CharField(max_length=255)),
                ('best_route', models.CharField(max_length=255)),
                ('current_location', models.CharField(max_length=255)),
                ('top_loc_name_dis_time', models.CharField(max_length=100000)),
            ],
        ),
        migrations.AddField(
            model_name='all_categories',
            name='chennai_categories',
            field=models.CharField(default='kj', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='all_categories',
            name='jaipur_categories',
            field=models.CharField(default='kj', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='all_categories',
            name='kolkata_categories',
            field=models.CharField(default='kj', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_categories',
            name='chennai_all_spots',
            field=models.CharField(default='kj', max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_categories',
            name='chennai_categories',
            field=models.CharField(default='kj', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_categories',
            name='delhi_all_spots',
            field=models.CharField(default='kj', max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_categories',
            name='jaipur_all_spots',
            field=models.CharField(default='kj', max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_categories',
            name='jaipur_categories',
            field=models.CharField(default='kj', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_categories',
            name='kolkata_all_spots',
            field=models.CharField(default='kj', max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_categories',
            name='kolkata_categories',
            field=models.CharField(default='kj', max_length=255),
            preserve_default=False,
        ),
    ]
