# Generated by Django 4.1.7 on 2023-05-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_chennai_user_output_jaipur_user_output_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Categories_Chennai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='All_Categories_Delhi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='All_Categories_Jaipur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='All_Categories_Kolkata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='All_Categories',
        ),
    ]
